# Generated by Django 4.2.2 on 2023-06-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubName', models.TextField(unique=True)),
                ('clubLogo', models.TextField()),
            ],
        ),
    ]
