# Generated by Django 4.2.2 on 2023-06-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='clubName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
