# Generated by Django 4.2.2 on 2023-07-12 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_access_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='clubName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='club',
            name='clubLogo',
        ),
        migrations.AddField(
            model_name='club',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('poster', models.ImageField(upload_to='')),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='base.club')),
            ],
        ),
    ]
