# Generated by Django 4.2.2 on 2023-07-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_clubname_club_name_remove_club_clublogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
