# Generated by Django 4.2.2 on 2023-07-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_event_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usn',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
