# Generated by Django 4.2.2 on 2023-07-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_usn'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventType',
            field=models.CharField(default='upcoming', max_length=255),
        ),
    ]
