# Generated by Django 4.2.2 on 2023-07-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_event_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='longDetails',
            field=models.TextField(null=True),
        ),
    ]
