# Generated by Django 4.1.7 on 2023-07-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_event_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='longDetails',
            field=models.TextField(null=True),
        ),
    ]
